baseURL = "https://ylyang-phy.github.io/"
publishDir = "public"

hasCJKLanguage = true

languageCode = "en-us"
title = "Yilun Yang"
theme = "anatole"
author = "Yilun Yang"

[menu]
	[[menu.main]]
		name = "About"
		identifier = "about"
		weight = 100
		url = "/"
    
	[[menu.main]]
		name = "Research"
		weight = 200
		identifier = "research"

	[[menu.main]]
        name = "Spectral filters"
        weight = 500
        url = "/research/filter"
        parent = "research"  

    [[menu.main]]
        name = "Quantum simulation"
        weight = 600
        url = "/research/qsim"
        parent = "research"  

[params]
    capitalizeListTitles = false
	title = "Yilun Yang's homepage"
	author = "Yilun Yang"
	description = """
	"""
	displayMode = "light"
	contentratio = 0.8
	doNotLoadAnimations = true
    math = true

	customCss = ["css/academicons.css"]
	favicon = "favicons/"

    mainSections = []

	[[params.socialIcons]]
		icon = "fas fa-envelope"
		title = "e-mail"
		url = "mailto:ylyang@berkeley.edu"

	[[params.socialIcons]]
		icon = "ai ai-google-scholar-square ai-3x"
		title = "Google Scholar"
		url = "https://scholar.google.com/citations?hl=en&user=WjY5YRYAAAAJ"



[markup]
	defaultMarkdownHandler = "goldmark"
  	[markup.asciidocExt]
    	backend = "html5"
		extensions = []
		failureLevel = "fatal"
		noHeaderOrFooter = true
		preserveTOC = false
		safeMode = "unsafe"
		sectionNumbers = false
		trace = false
		verbose = false
		workingFolderCurrent = false
		[markup.asciidocExt.attributes]
  	[markup.goldmark]
    	[markup.goldmark.extensions]
			definitionList = true
			footnote = true
			linkify = true
			strikethrough = true
			table = true
			taskList = true
			typographer = true
			[markup.goldmark.extensions.passthrough]
				enable = true
				[markup.goldmark.extensions.passthrough.delimiters]
				block = [['$$', '$$']]
				inline = [['\(', '\)']]
    	[markup.goldmark.parser]
			autoHeadingID = true
			autoHeadingIDType = "github"
			[markup.goldmark.parser.attribute]
				block = false
				title = true
    	[markup.goldmark.renderer]
			hardWraps = false
			unsafe = true
			xhtml = false
  	[markup.highlight]
		anchorLineNos = false
		codeFences = true
		guessSyntax = false
		hl_Lines = ""
		lineAnchors = ""
		lineNoStart = 1
		lineNos = false
		lineNumbersInTable = true
		noClasses = true
		style = "monokai"
		tabWidth = 4